# Generated by Django 3.2.3 on 2021-07-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Gender',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
